name: Test Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: make test-short
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        REDIS_STREAMS_URL: redis://localhost:6379
        REDIS_MEMORY_URL: redis://localhost:6379

    - name: Run coverage
      run: make test-coverage
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        REDIS_STREAMS_URL: redis://localhost:6379
        REDIS_MEMORY_URL: redis://localhost:6379